### ISSUE TITLE
ID Issue

### ISSUE THREAD

**Issue by heeshala** [ryanhz/nfc_emulator#4]
// Start NFC emulator with AID, cardUid, and optional AES key:
await NfcEmulator.startNfcEmulator("666B65630001", "cd22c716", "79e64d05ed6475d3acf405d6a9cd506b");

When i replace the UID with the card id that i read from the reader 
The emulated card is completely different .
Any way of solving it
Thank you

**Comment by ryanhz** [comment]
Hi @heeshala 
The NFC Emulator was written mainly for the Cidron reader (the AID is in the example):
http://www.civintec.com/info_22.aspx?itemid=35

their reader is using peer-to-peer mode to exchange data, which includes the encrypted card UID, the reader requires UID to be AES encrypted.

You can't emulate the UID you selected, the Android phone will always generates a random UID (that is the case for most Android phone).  The only way to send over a UID is via P2P mode, like the example.

**Comment by heeshala** [comment]
> Hi @heeshala
> The NFC Emulator was written mainly for the Cidron reader (the AID is in the example):
> http://www.civintec.com/info_22.aspx?itemid=35
> 
> their reader is using peer-to-peer mode to exchange data, which includes the encrypted card UID, the reader requires UID to be AES encrypted.
> 
> You can't emulate the UID you selected, the Android phone will always generates a random UID (that is the case for most Android phone). The only way to send over a UID is via P2P mode, like the example.

Thank you for the reply 
I am on a project where i have 13.5MHz NFC cards which are readable by mobile phones as well they act as physical passes i only get the hexadecimal id eg ```0x012e41312a8a4243``` from the card the thing is that i want to be able to store the card by shared preferences in the app and use the app instead of the physical card to be read by the reader. Just like a wallet. Is there any possibility for it. Its for aa project and its a great help

**Comment by ryanhz** [comment]
@heeshala  there is no problem for mobile app to read NFC card, even for iPhone.  But for emulate a physical card, there is another story, iPhone is complete out of the question, Android will generate random UID for secure reason.   If your physical 
 card reader work in P2P mode or it can other part of data instead of solely the UID for authentication, then that is possible that you can use your phone to act like a card.

**Comment by braysonjohn148** [comment]
How can I decode and get a value that determines the random id created belongs to which user?

**Comment by braysonjohn148** [comment]
> Hi @heeshala The NFC Emulator was written mainly for the Cidron reader (the AID is in the example): http://www.civintec.com/info_22.aspx?itemid=35
> 
> their reader is using the peer-to-peer mode to exchange data, which includes the encrypted card UID, the reader requires UID to be AES encrypted.
> 
> You can't emulate the UID you selected, the Android phone will always generate a random UID (that is the case for most Android phones). The only way to send over a UID is via P2P modes, like in the example.

But how can the reader know the exact device/user that has tapped? Is there anything that can uniquely define the tapped device?

**Comment by ryanhz** [comment]
> How can I decode and get a value that determines the random id created belongs to which user?

The reader is using peer-to-peer mode to exchange data, the phone can transmit the encrypted AES encrypted UID (in the payload) to identity a user.

**Comment by ryanhz** [comment]
> > Hi @heeshala The NFC Emulator was written mainly for the Cidron reader (the AID is in the example): http://www.civintec.com/info_22.aspx?itemid=35
> > their reader is using the peer-to-peer mode to exchange data, which includes the encrypted card UID, the reader requires UID to be AES encrypted.
> > You can't emulate the UID you selected, the Android phone will always generate a random UID (that is the case for most Android phones). The only way to send over a UID is via P2P modes, like in the example.
> 
> But how can the reader know the exact device/user that has tapped? Is there anything that can uniquely define the tapped device?

The reader can read the encrypted AES encrypted UID.  It support OSDP protocol.

**Comment by braysonjohn148** [comment]
So when the emulated UID is decrypted using AES, we can get the same exact UID we set during startNfcEmulator(). Because I am using ESP32 where I can encrypt/decrypt AES, PN532 as an NFC device allows peer-to-peer communication.

**Comment by ryanhz** [comment]
Yes, it is possible to use ESP32 and PN532 to read the decrypted emulated UID.  You can even customise the exchanging data format in processCommandApdu() method.  This package is mainly made for the CIDRON reader.
